version: 2
jobs:
  checkout_and_install:
    docker:
      - image: nixos/nix:2.3.6
    working_directory: ~/protocol
    steps:
      - checkout
      - restore_cache:
          keys:
            - solc_0_6_12-dapptools_0_41_0
      - run:
          name: Install DappTools
          command: |
            nix-env -i git
            nix-env -iA solc-versions.solc_0_6_12 -if https://github.com/dapphub/dapptools/tarball/hevm/0.41.0
      - save_cache:
          key: solc_0_6_12-dapptools_0_41_0
          paths:
            - /nix

workflows:
  version: 2
  build:
    jobs:
      - checkout_and_install