version: 2
jobs:
  install_dapptools:
    docker:
      - image: nixos/nix:2.3.6
    working_directory: ~/protocol
    steps:
      - restore_cache:
          keys:
            - solc_0_6_12-dapptools_0_41_0
      - run:
          name: Install DappTools
          command: |
            nix-env -i cachix git
            cachix use dapp
            nix-env -iA dapp hevm seth solc solc-versions.solc_0_6_12 -f https://api.github.com/repos/dapphub/dapptools/tarball/hevm/0.41.0
      - save_cache:
          key: solc_0_6_12-dapptools_0_41_0
          paths:
            - /nix
  build_and_test:
    working_directory: ~/protocol
    docker:
      - image: nixos/nix:2.3.6
    steps:
      - restore_cache:
          keys:
            - solc_0_6_12-dapptools_0_41_0
      - run:
          name: build
          command: |
            dapp build

workflows:
  version: 2
  build:
    jobs:
      - install_dapptools
      - build_and_test